
import Navbar from "@/components/Navbar";
import "./globals.css";
import { MyContext } from "./context";
import ProfileIcon from "@/components/ProfileIcon";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <MyContext>
          <Navbar />
          <ProfileIcon />
          {children}
        </MyContext>
      </body>
    </html>
  );
}
